version: "2.1"
services:
  cab-service:
    image: cab-service
    ports:
      - 9090:9090
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./database:/cab_bookings
    ports:
      - 27017:27017